baseurl = "https://simecek.github.io/shredded_code/"
relativeurls = true
languageCode = "en-us"
title = "Shredded Code"
theme = "hugo-theme-slim"
googleAnalytics = "UA-90647482-1"
disqusShortname = "https-simecek-github-io-blog"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Personal page"
    url = "https://simecek.github.io"
[[menu.main]]
    name = "Source code"
    url = "https://github.com/simecek/shredded_code"

[params]
    description = "A website built through Hugo and blogdown."
    disqus_url = "https://simecek.github.io/"
    AnalyticsID = "UA-90647482-1"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 100
    height = 100
    alt = "Logo"
